version: "3"

services:
  mongo-normas-mock:
    container_name: mongo-normas-mock
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db

  backend-api-normas-mock:
    container_name: backend-api-normas-mock
    build: ./backend
    command: "node server.js"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo-normas-mock"

