version: "3"

services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./data:/data/db

  backend-api:
    container_name: backend-api
    build: ./backend
    command: "node server.js"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"

